services:

  sample_go:
    image: template.utils/sample-go
    build: ./app/sample_go
    volumes:
      - ./app/sample_go/src:/app

  sample_py:
    image: template.utils/sample-py
    build: ./app/sample_py
    volumes:
      - ./app/sample_py/src:/app

  sample_db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - sample_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  sample_data:
