name: "🐛 Bug Report"
description: "Report a bug in the project."
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Explain the issue here..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What you expected to happen."
      placeholder: "Describe the expected outcome."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened."
      placeholder: "Describe what actually occurred."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "🌍 Environment"
      description: "Provide information about your environment (OS, browser, etc.)."
      placeholder: "e.g., Windows 10, Chrome 100.0"

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots (if applicable)"
      description: "Add screenshots to help explain the problem."
      placeholder: "Upload screenshots here."

  - type: checkboxes
    id: additional_info
    attributes:
      label: "🚀 Additional Information"
      description: "Any other context about the problem."
      options:
        - label: "I have checked for duplicate issues."
        - label: "I have tried debugging the issue myself."
