name: Auto Format

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/src/**/*.ts'
      - 'app/src/**/*.tsx'
      - 'app/src/**/*.js'
      - 'app/src/**/*.jsx'
      - 'app/src/**/*.json'
      - 'app/src/**/*.md'

jobs:
  format:
    name: Auto Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run ESLint with auto-fix
        working-directory: ./app
        run: npm run lint

      - name: Run Prettier
        working-directory: ./app
        run: npm run format

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "refactor: auto-format code [skip ci]"
          git push
